'use strict';

const artiPart1Data = [
  {
    'id': 'pr',
    'origin': 'France',
    'price': 2,
    'unit': 'Pièce',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'banane',
    'origin': 'Guyane',
    'price': 0.99,
    'unit': 'Grappe',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'civ',
    'origin': 'angleterre',
    'price': 0.85,
    'unit': 'Pièce',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'cij',
    'origin': 'Guyane',
    'price': 1.25,
    'unit': 'Pièce',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'curry',
    'origin': 'Inde',
    'price': 3.6,
    'unit': 'kg',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'oignon',
    'origin': 'Ukraine',
    'price': 1.51,
    'unit': 'Pièce',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'entrecote',
    'origin': 'France',
    'price': 18,
    'unit': 'kg',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'nuggets',
    'origin': 'France',
    'price': 3,
    'unit': 'Sachet',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'wings',
    'origin': 'France',
    'price': 2.95,
    'unit': 'Sachet',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'poulet',
    'origin': 'Espagne',
    'price': 4.99,
    'unit': 'Pièce',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 're',
    'origin': 'Ireland',
    'price': 15,
    'unit': 'kg',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'pj',
    'origin': 'France',
    'price': 2,
    'unit': 'Pièce',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'po',
    'origin': 'France',
    'price': 2,
    'unit': 'Pièce',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'or',
    'origin': 'Maroc',
    'price': 1.5,
    'unit': 'kg',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'av',
    'origin': 'Pérou',
    'price': 1.5,
    'unit': 'Pièce',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'fr',
    'origin': 'France',
    'price': 3,
    'unit': 'Barquette 250g',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'fr',
    'origin': 'France',
    'price': 5,
    'unit': 'Barquette 500g',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'fr',
    'origin': 'Espagne',
    'price': 8,
    'unit': 'Plateau 1kg',
    'quantity': '',
    'inCart': false,
  },
  {
    'id': 'pa',
    'origin': 'Maroc',
    'price': 3,
    'unit': 'kg',
    'quantity': '',
    'inCart': false,
  },
];

const integerUnits = {
  'kg': false,
  'g': false,
  'Pièce': true,
  'Barquette 250g': true,
  'Barquette 500g': true,
  'Plateau 1kg': true,
};